# Generated by Django 5.1.4 on 2025-03-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'verbose_name_plural': 'Subject Marks'},
        ),
    ]
