# Generated by Django 5.1.4 on 2025-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
