# Generated by Django 5.1.4 on 2025-03-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_player_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dob',
        ),
    ]
