# Generated by Django 5.1.4 on 2025-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_views',
            field=models.IntegerField(null=True),
        ),
    ]
