# Generated by Django 5.1.4 on 2025-03-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_recipe_recipe_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
